# Generated by Django 2.2 on 2019-04-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='actor',
            field=models.CharField(default='演员', max_length=50),
        ),
    ]
